### ISSUE TITLE
installp后cp config后无法正常扫描

### ISSUE THREAD

**Issue by spacex-3** [ayasa520/TaskScheduler#1]
[WARNING][2024-12-18 10:59:23][plugin_manager.py:113] - Failed to import plugin TaskScheduler: unsupported operand type(
s) for |: 'type' and 'NoneType'

**Comment by ayasa520** [comment]
fresh install 无法复现
![image](https://github.com/user-attachments/assets/b8deb636-8ba2-46d7-b284-625e9edef9e0)

**Comment by spacex-3** [comment]
奇怪，requirement也安装了，我晚点试试再，谢谢啦

**Comment by ayasa520** [comment]
我明白了,你使用的 Python 版本是不是比较旧?(低于 3.10)

我在代码中使用了类似 `def get_trigger(self, cycle: str, time_str: str | None = None)` 的类型标注, 3.10 之前版本不支持这个写法, 而应该用 `Union[str,None]` 或者 `Optional[str]`

**Comment by spacex-3** [comment]
是的，3.9.2，之前3.10用其他插件容易出问题

**Comment by ayasa520** [comment]
我更新了代码, 可以再试一下

**Comment by spacex-3** [comment]
感谢佬，可以了！

**Comment by spacex-3** [comment]
对了想问问由于调试需要，经常需要#scanp，这样导致重复的发送定时任务，有可能避免么？还是说只能ctrl c退出 cow重新运行。。

**Comment by ayasa520** [comment]
> 对了想问问由于调试需要，经常需要#scanp，这样导致重复的发送定时任务，有可能避免么？还是说只能ctrl c退出 cow重新运行。。

我的两个 PR(https://github.com/zhayujie/chatgpt-on-wechat/pull/2413, https://github.com/zhayujie/chatgpt-on-wechat/pull/2407) 已经被合并了, 在最新的 chatgpt-on-wechat 中应该不会出现重复的问题. 运行scanp 命令时可以看到 `[TaskScheduler] 关闭 scheduler` 的日志, 这就代表是正常的

**Comment by spacex-3** [comment]
是否意味着其他用scheduler的插件也是在最新版不会重复出现了？

**Comment by spacex-3** [comment]
实测，还是很多重复通知。。。

<img width="832" alt="image" src="https://github.com/user-attachments/assets/7d589ea9-4918-4f69-98c5-17d6461c0ffb" />

**Comment by spacex-3** [comment]
是否是这段代码起的作用，谢谢大佬：

`
class TaskScheduler(Plugin):
--
90 | def __del__(self):
91 | logger.info("[TaskScheduler] 关闭 scheduler")
92 | self.scheduler.shutdown()

`

**Comment by ayasa520** [comment]
@spacex-3 这是什么插件？

**Comment by ayasa520** [comment]
> 是否是这段代码起的作用，谢谢大佬：
> 
> ## `
> class TaskScheduler(Plugin):
> 90 | def **del**(self): 91 | logger.info("[TaskScheduler] 关闭 scheduler") 92 | self.scheduler.shutdown()
> 
> `

是的
